### ISSUE TITLE
Interface 'IFormGroup<T>' incorrectly extends interface 'IAbstractControl<T, T>'

### ISSUE THREAD

**Issue by msegmx** [rxweb/rxweb#352]
# Describe the bug
I've created a new Angular 10 project with --strict parameter set.

I get this error :

```
Compiling TypeScript sources through ngc
ERROR: node_modules/@rxweb/types/reactive-form/i-form-group.d.ts:3:18 - error TS2430: Interface 'IFormGroup<T>' incorrectly extends interface 'IAbstractControl<T, T>'.
  Types of property 'patchValue' are incompatible.
    Type '(value: Partial<T>, options?: { onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined) => void' is not assignable to type '(value: T | null, options?: { onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolean | undefined; emitViewToModelChange?: boolean | undefined; } | undefined) => void'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'T | null' is not assignable to type 'Partial<T>'.
          Type 'null' is not assignable to type 'Partial<T>'.

3 export interface IFormGroup<T> extends IAbstractControl<T, T> {
                   ~~~~~~~~~~

An unhandled exception occurred: node_modules/@rxweb/types/reactive-form/i-form-group.d.ts:3:18 - error TS2430: Interface 'IFormGroup<T>' incorrectly extends interface 'IAbstractControl<T, T>'.
  Types of property 'patchValue' are incompatible.
    Type '(value: Partial<T>, options?: { onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined) => void' is not assignable to type '(value: T | null, options?: { onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolean | undefined; emitViewToModelChange?: boolean | undefined; } | undefined) => void'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'T | null' is not assignable to type 'Partial<T>'.
          Type 'null' is not assignable to type 'Partial<T>'.

3 export interface IFormGroup<T> extends IAbstractControl<T, T> {
                   ~~~~~~~~~~
```

# Expected Behavior

# To Reproduce
Open a fresh Stackblitz Angular 10 project and add "@rxweb/types" as a dependency =>  compilation fails with : 

```
Error in ~/src/main.ts
ngcc failed to run on @rxweb/types@1.0.3.
```

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/<package-name>@<packageversion>

"@rxweb/types": "^1.0.3"

Angular CLI: 10.0.0
Node: 12.18.1
OS: linux x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0
@angular-devkit/build-angular      0.1000.0
@angular-devkit/build-ng-packagr   0.1000.0
@angular-devkit/build-optimizer    0.1000.0
@angular-devkit/build-webpack      0.1000.0
@angular-devkit/core               10.0.0
@angular-devkit/schematics         10.0.0
@angular/cdk                       10.0.0
@angular/cli                       10.0.0
@ngtools/webpack                   10.0.0
@schematics/angular                10.0.0
@schematics/update                 0.1000.0
ng-packagr                         10.0.0
rxjs                               6.5.5
typescript                         3.9.5
webpack                            4.43.0

**Comment by ajayojha** [comment]
@msegmx Thanks for reporting this I will check and resolve the same ASAP.

**Comment by msegmx** [comment]
Thanks for your quick response.

I'm not sure if it's the same error (can't see details on Stackblitz) but simply adding a dependency to "@rxweb/types" to a new Angular 10 project fails to compile.

**Comment by ajayojha** [comment]
Ok I will check and let you know, thanks you have shared enough information to drill down the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajayojha** [comment]
@msegmx I have released the new version of [@rxweb/types](https://www.npmjs.com/package/@rxweb/types)(1.0.4) and the issue has been fixed in the respective release. Please update the package.

Please let me know if there is any issue :)

**Comment by msegmx** [comment]
Compiled on my local computer without error. But I still get an error on Stackblitz, after creating an Angular 10 project and adding @rxweb/types as a dependency : 

```
Error in ~/src/main.ts
ngcc failed to run on @rxweb/types@1.0.4.
```

**Comment by ajayojha** [comment]
Please mark enable ivy false in the settings tabs of stackblitz code editor:
![image](https://user-images.githubusercontent.com/20392302/86145476-97dffb80-bb14-11ea-8625-34e113d9ec15.png)

**Comment by msegmx** [comment]
It installed without error, but I don't use Stackblitz anyway.

I have another issue though :

in TS:
`wControl: IFormControl<boolean> = new FormControl();`
in HTML Template:
`<input [formControl]="wControl" type="checkbox" />`
I get this error :

`error TS2739: Type 'IFormControl<boolean>' is missing the following properties from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormState`

**Comment by ajayojha** [comment]
@msegmx Sorry for this, let me check end to end case.

**Comment by msegmx** [comment]
Since this compilation error is solved, I close this issue and wait for a new version.

**Comment by ajayojha** [comment]
@msegmx Thanks, fixed in the latest release (1.0.5).

**Comment by msegmx** [comment]
It works. Thanks!
