### ISSUE TITLE
rx-select with freetext

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#394]
# Describe the bug
Issue 1:  when we enter free text (the text which not available in drop down) and press up key then it will get error in console
i have attached screenshot of it
![issue01](https://user-images.githubusercontent.com/48114976/91445512-d59e9d80-e893-11ea-914c-120dc86d758c.png)

Issue 02 : when we click on drop down but not select any value  from dropdown and go to another component then it will shows error in console.
![issue02](https://user-images.githubusercontent.com/48114976/91445868-5067b880-e894-11ea-8363-e965d7cbd5fa.png)

# Expected Behavior
don't give error in console

# To Reproduce
Issue 01: enter any text in drop down (which is not present in drop down) press up key from keyboard. see error in console.

issue 02 : click on drop down and then click on click here button it will show error in console.

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/angular-rx-select-check2?file=src%2Fapp%2Fapp.component.ts

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by ajayojha** [comment]
@afzalmansuri the issue has been fixed in the latest version(0.0.5), please update the same. I have updated the package in the provided [stackblitz example ](https://stackblitz.com/edit/angular-rx-select-check2-zn5p8o?file=src%2Fapp%2Fapp.component.ts) and this is working fine. please refer to the same.

**Comment by afzalmansuri** [comment]
Hello sir as per provided example i have update the project package then issue is resolved but Issue 01 didn't resolve yet 
While i have enter any free text and press enter it gives error.
see i have attached screenshot of it
![image](https://user-images.githubusercontent.com/48114976/94404605-e9883880-018c-11eb-88aa-e3dcceae61a1.png)

**Comment by ajayojha** [comment]
@afzalmansuri I tried with the mentioned first step in the example but there is no error, can you please mention the steps again, if the issue occurs with the different use case.

**Comment by afzalmansuri** [comment]
Enter free text (which is not present in drop down) then press enter

**Comment by ajayojha** [comment]
@afzalmansuri The issue is fixed in the 0.0.7 release. Please update the same.

**Comment by afzalmansuri** [comment]
Thanks @ajayojha sir working fine now but when we enter \ (Backslash ) it gives the below RegExp error
![image](https://user-images.githubusercontent.com/48114976/95042751-79cbfd80-06f8-11eb-8578-3d0ba5277024.png)

for reproduce step enter \ (Backslash) in dropdown

**Comment by afzalmansuri** [comment]
Hello @ajayojha sir any update for above issue ?

**Comment by ajayojha** [comment]
@afzalmansuri I am sorry for the delayed response, I have released the new version of 0.0.14, please update the same, it's working fine.
