### ISSUE TITLE
Not compatible with Angular 10.1

### ISSUE THREAD

**Issue by DarkDrek** [rxweb/rxweb#398]
# Describe the bug
At least "@rxweb/reactive-form-validators" is not compatible with Angular 10.1 and produces a build error.

```
ERROR in node_modules/@rxweb/reactive-form-validators/services/form-control.d.ts:46:5 - error TS2610: 'dirty' is defined as an accessor in class 'FormControl', but is overridden here in 'RxFormControl' as an instance property.

46     dirty: boolean;
```

# Expected Behavior
It should not produce a build error.

# To Reproduce
Add "@rxweb/reactive-form-validators" to a Angular 10.1 project and run `ng build`

# Package Version
@rxweb/reactive-form-validators@2.1.0

**Comment by ajayojha** [comment]
@DarkDrek please check with 2.0.0 version of reactive form validators

**Comment by DarkDrek** [comment]
Same error with 2.0.0 but I found that it is an error with TypeScript 4.0
https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#typescript-40

**Comment by ajayojha** [comment]
@DarkDrek Thanks for sharing the link, I was aware but I was thinking on a different angle while suggesting the version 2.0.0, but now all OK, Will fix and release it soon. For now, you can remove the 'dirty' property from the 'RxFormControl' class in the source map file. This is just a temporary quick and dirty solution :).

**Comment by vrait35** [comment]
when will the update be released?

**Comment by ajayojha** [comment]
@vrait35 this will be released in the next two days.

**Comment by aupaul** [comment]
@ajayojha let us know when the fix is released

**Comment by vrait35** [comment]
@ajayojha , ok

**Comment by ajayojha** [comment]
@DarkDrek & @vrait35 The issue has been fixed in 2.1.1 release, please update the package.

**Comment by juaal12** [comment]
> @DarkDrek & @vrait35 The issue has been fixed in 2.1.1 release, please update the package.

Still happening to me... I got the last release 2.1.1 and the error still showing up when executing ng build. 

```
ERROR in node_modules/@rxweb/reactive-form-validators/services/form-control.d.ts:46:14 - error TS2610: 'dirty' is defined as an accessor in class 'FormControl', but is overridden here in 'RxFormControl' as an instance property.

      46     readonly dirty: boolean;
```
