### ISSUE TITLE
Rx-tag sequence issue after selecting option

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#414]
# Bug
When any option is selected in rx-tag and then the same option is deselected then that option gets pushed to the last index of given options list which changes the actual sequence. This is related to previous bug:- [#413](https://github.com/rxweb/rxweb/issues/413)

# Expected Behavior
When any option is selected and that same option is deselected then it should retain its original position in given options sequence. For example, any option is selected which comes 3rd in sequence and that same option is deselected then it should again get appended at 3rd position rather than last position.

# Url (stackblitz)
https://stackblitz.com/edit/rxtag-disable-sorting-enwhoe?file=src/app/hello.component.ts

# Package Version
@rxweb/angular@0.0.7

**Comment by ajayojha** [comment]
@mitanshu-patel It will be in the last if the sorting is allowed, hence I am closing this ticket as no action required on this.

**Comment by mitanshu-patel** [comment]
@ajayojha  Sorting issue still persists. If sorting is kept true i.e. if `[isSort]=false` **isn't used** then it does random sorting and now if we **use** `[isSort]=false`  then it generates sequence issue as it **appends the option in last position**(as mentioned in this ticket), when same option is selected and then deselected.

**Comment by ajayojha** [comment]
Please use the version of 0.0.10, the issue is fixed in that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mitanshu-patel** [comment]
> @ajayojha Sorting issue still persists. If sorting is kept true i.e. if `[isSort]=false` **isn't used** then it does random sorting and now if we **use** `[isSort]=false` then it generates sequence issue as it **appends the option in last position**(as mentioned in this ticket), when same option is selected and then deselected.

@ajayojha . I've update rxweb/angular version to 0.0.10 as you suggested. But still facing this same issue. 
For reference:-
https://stackblitz.com/edit/rxtag-disable-sorting-enwhoe?file=src/app/hello.component.ts

**Comment by ajayojha** [comment]
@ajayojha Please update the package with the version of 0.0.17, please refer to the working example: https://stackblitz.com/edit/rxtag-disable-sorting-1pe7zx?file=src%2Fapp%2Fuser-model.ts

**Comment by mitanshu-patel** [comment]
Ok thanks, working fine now
