### ISSUE TITLE
reactive-form-validators  - build fail when importing RxReactiveFormsModule

### ISSUE THREAD

**Issue by kfirufk** [rxweb/rxweb#460]
Hi.
I have Angular CLI 11.0.6 project
when I add @rxweb/reactive-form-validators v2.1.2 to the project, and import it in my project the build fails with:

```
Error: ./node_modules/@rxweb/reactive-form-validators/fesm2015/rxweb-reactive-form-validators.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@rxweb/reactive-form-validators/fesm2015/rxweb-reactive-form-validators.js: Column must be greater than or equal to 0, got -15
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:543:13)
    at BasicSourceMapConsumer.SourceMapConsumer_allGeneratedPositionsFor [as allGeneratedPositionsFor] (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:201:22)
    at /Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/lib/transformation/file/merge-map.js:186:27
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at buildMappingData (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/lib/transformation/file/merge-map.js:147:12)
    at mergeSourceMap (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/lib/transformation/file/merge-map.js:21:17)
    at generateCode (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/lib/transformation/file/generate.js:74:39)
    at run (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)
    at Function.transform (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/gensync/index.js:261:32)
    at /Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Volumes/osx-storage/projects/tux-in/mycocktailworld/mycocktailworld-client/node_modules/gensync/index.js:223:11)

```
this is my package.json:

```
{
  "name": "mycocktailworld-client",
  "version": "0.0.0",
  "scripts": {
    "postinstall": "ngcc",
    "ng": "ng",
    "start": "ng serve  --configuration=en",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run mycocktailworld-client:serve-ssr",
    "serve:ssr": "node dist/mycocktailworld-client/server/main.js",
    "build:ssr": "ng build --prod && ng run mycocktailworld-client:server:production",
    "prerender": "ng run mycocktailworld-client:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular-material-extensions/password-strength": "^8.1.0",
    "@angular-material-extensions/select-country": "^4.0.1",
    "@angular/animations": "~11.0.8",
    "@angular/cdk": "^11.0.3",
    "@angular/common": "~11.0.8",
    "@angular/compiler": "~11.0.8",
    "@angular/core": "~11.0.8",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "~11.0.8",
    "@angular/material": "^11.0.3",
    "@angular/platform-browser": "~11.0.8",
    "@angular/platform-browser-dynamic": "~11.0.8",
    "@angular/platform-server": "~11.0.8",
    "@angular/router": "~11.0.8",
    "@apollo/client": "^3.0.0",
    "@ngneat/until-destroy": "^8.0.3",
    "@nguniversal/express-engine": "^11.0.1",
    "@rxweb/reactive-form-validators": "^2.1.2",
    "@sweetalert2/ngx-sweetalert2": "^9.0.0",
    "@swimlane/ngx-charts": "^16.0.0",
    "@tinymce/tinymce-angular": "^4.2.0",
    "angulartics2": "^10.0.0",
    "apollo-angular": "^2.2.0",
    "apollo-link-context": "^1.0.20",
    "apollo-link-error": "^1.1.13",
    "compression": "^1.7.4",
    "cookieconsent": "^3.1.1",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "graphql": "^15.0.0",
    "graphql-tag": "^2.11.0",
    "moment": "^2.29.1",
    "ng-recaptcha": "^7.0.1",
    "ngx-avatar": "^4.0.0",
    "ngx-cookieconsent": "^2.2.3",
    "ngx-mask": "^11.1.4",
    "ngx-timeago": "^2.0.0",
    "rxjs": "~6.6.0",
    "spdy": "^4.0.2",
    "svg-country-flags": "^1.2.9",
    "sweetalert2": "^10.13.0",
    "tinymce": "^5.6.2",
    "tslib": "^2.0.0",
    "zen-observable": "^0.8.15",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.6",
    "@angular-eslint/builder": "0.8.0-beta.3",
    "@angular-eslint/eslint-plugin": "0.8.0-beta.3",
    "@angular-eslint/eslint-plugin-template": "0.8.0-beta.3",
    "@angular-eslint/schematics": "^0.8.0-beta.3",
    "@angular-eslint/template-parser": "0.8.0-beta.3",
    "@angular/cli": "~11.0.6",
    "@angular/compiler-cli": "~11.0.8",
    "@angular/localize": "^11.0.8",
    "@nguniversal/builders": "^11.0.1",
    "@types/compression": "^1.7.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "@types/spdy": "^3.4.4",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "codelyzer": "^6.0.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "source-map-support": "^0.5.19",
    "ts-node": "~8.3.0",
    "typescript": "~4.0.2"
  }
}

```

**Comment by ajayojha** [comment]
@kfirufk it's working please refer to this repo https://github.com/ajayojha/build-issue-rxweb-angular

**Comment by ajayojha** [comment]
@kfirufk  I am closing this ticket as there is no further update on this, feel free to reopen this ticket or create a new ticket if you have any concern.

**Comment by zavadmar** [comment]
Hi,
I had same problem and I've solved it by changing target value in tsconfig.json from es5 to es2015.

new tsconfig.json setting:
```
{
"compilerOptions": {
    "target": "es2015",
...
```
Maybe it helps someone.

**Comment by lkachun9129** [comment]
> Hi,
> I had same problem and I've solved it by changing target value in tsconfig.json from es5 to es2015.
> 
> new tsconfig.json setting:
> 
> ```
> {
> "compilerOptions": {
>     "target": "es2015",
> ...
> ```
> 
> Maybe it helps someone.

Without `es5` support, IE 11 is excluded from using this library with Angular > 10.

**Comment by Jrubzjeknf** [comment]
This issue still occurs, even with `"target": "es2015"`. Unfortunately I'm unable to determine why or how it occurs. In a clean web app, it works fine, but it fails in our web app with multiple Angular libraries.

**Comment by Jrubzjeknf** [comment]
The issue is reproducable by setting the `target` to `es5`. [I created a repo where the issue can be reproduced, with steps.](https://github.com/Jrubzjeknf/rxweb-reactive-form-validators-build-failure)

When this issue is solved for es5, it will most probably also be solved for other targets which are harder to reproduce.

@ajayojha Can this issue please be reopened?

**Comment by ajayojha** [comment]
@Jrubzjeknf Thanks for providing the repo. Will update here as soon as I have something.

**Comment by Jrubzjeknf** [comment]
If it helps, another library [fixed this issue this way](https://github.com/stalniy/casl/commit/771526379ff8203170a433d71b68644a48ff44eb).

**Comment by piero1903** [comment]
This error is blocking us. Is there any news?

**Comment by ajayojha** [comment]
this has been fixed in the new release, kindly update the package.

**Comment by velkvik** [comment]
Hello @ajayojha

I have an Angular CLI: 10.0.0 project with "@rxweb/reactive-form-validators": "^2.1.3" and  compilerOptions  target "es5".
Unfortunately I still get the same error: 

`...\node_modules\@rxweb\reactive-form-validators\__ivy_ngcc__\fesm2015\rxweb-reactive-form-validators.js: Column must be greater than or equal to 0, got -16`

Is reactive-form-validators not supported for es5?

Thank you and kind regards!

**Comment by prema6** [comment]
change the target from 'es5' to 'es2015'
